export { readState } from "./state.js";
export { computeStressIndex } from "./stress.js";
export { parseEmoBarTag } from "./parser.js";
export { analyzeBehavior, analyzeSegmentedBehavior, computeDivergence, analyzeDeflection } from "./behavioral.js";
export { computeDesperationIndex } from "./desperation.js";
export { calibrate, MODEL_PROFILES } from "./calibration.js";
export { computeRisk } from "./risk.js";
export { mapEmotionWord, classifyImpulse, analyzeSomatic, computeCrossChannel } from "./crossvalidation.js";
export { formatState, formatCompact, formatMinimal } from "./display.js";
export { configureStatusLine, restoreStatusLine } from "./setup.js";
export type { EmotionalState, EmoBarState, BehavioralSignals, MisalignmentRisk, SegmentedBehavior, DeflectionSignals, ImpulseProfile, SomaticProfile, CrossChannelResult } from "./types.js";
export { STATE_FILE } from "./types.js";
